In [11]:
variable2 = ['ID', 'Name', 'Depth', 'Latitude', 'Longitude']

In [13]:
print(variable2[0])

ID


In [9]:
for element in variable2:print(element)

ID
Name
Depth
Latitude
Longitude


In [1]:
i = 1

In [ ]:
while i <= 6:
    print(i)
    i += 1

In [21]:
import numpy as np

In [22]:
x = np.arange(15, dtype=np.int64).reshape(3, 5)
x[1:, ::2] = -99
x

array([[  0,   1,   2,   3,   4],
       [-99,   6, -99,   8, -99],
       [-99,  11, -99,  13, -99]])

In [25]:
array_1d=np.arange(12)
print(array_1d)

[ 0  1  2  3  4  5  6  7  8  9 10 11]


In [29]:
array_2d=np.arange(12).reshape(12,1)
print(array_2d)

[[ 0]
 [ 1]
 [ 2]
 [ 3]
 [ 4]
 [ 5]
 [ 6]
 [ 7]
 [ 8]
 [ 9]
 [10]
 [11]]


In [ ]:
import pandas

In [1]:
pwd

'/home/virtue/Python'